DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE addresses (
  id SERIAL PRIMARY KEY NOT NULL,
  users_id INTEGER,
  country VARCHAR(255) NOT NULL,
  province VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  street VARCHAR(255) NOT NULL,
  postal_code VARCHAR(255) NOT NULL
);

CREATE TABLE cars (
  id SERIAL PRIMARY KEY NOT NULL,
  make VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  year SMALLINT NOT NULL,
  mileage INTEGER NOT NULL,
  description TEXT,
  price INTEGER,
  image_url VARCHAR(255) NOT NULL,
  availability BOOLEAN,
  owner_id INTEGER NOT NULL
);

CREATE TABLE messages (
id SERIAL PRIMARY KEY NOT NULL,
buyer_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
car_id INTEGER REFERENCES cars(id) ON DELETE CASCADE,
message TEXT
);

CREATE TABLE favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL,
  cars_id INTEGER NOT NULL,
  favourite BOOLEAN
);


